pipeline {
    agent any

    environment {
        TEST1 = "test_value1"
        TEST2 = "test_value2"
    }
    stages {
        stage('Build') { 
            
            steps {
                echo "This is Build stage."
                sh 'sleep 10'
                echo '$TEST1'
            }
        }
        stage('Test') { 
            steps {
                echo "This is Test stage." 
                sh ''' 
                    #!/bin/bash
                    ls -lrt
                    sleep 10
                    echo $TEST2
                '''
            }
        }
        stage('Deploy') { 
            steps {
                echo "This is Deploy stage." 
            }
        }
    }
}