pipeline {
    
    stages {
        stage('Build') { 
            agent {
                label 'Node_Label_1'
            }
            steps {
                echo "This is Build stage."
                sh 'sleep 10'
            }
        }
        stage('Test') { 
            agent any
            steps {
                echo "This is Test stage." 
                sh ''' 
                    #!/bin/bash
                    ls -lrt
                    sleep 10
                '''
            }
        }
        stage('Deploy') { 
            steps {
                echo "This is Deploy stage." 
            }
        }
    }
}