pipeline {
    agent any
     environment {
        TEST1 = "test_value1"
        TEST2 = "test_value2"
    }
    stages {
        stage('Build') { 

            environment {
                BUILD_STAGE1 = "my_build1"
                BUILD_STAGE2 = "my_build2"
            }
            
                steps {
                    echo "This is Build stage."
                    sh '''
                        #!/bin/bash
                        echo $BUILD_STAGE1
                        sleep 5 
                    '''
                }
        }
        stage('Test') { 
            steps {
                echo "This is Test stage." 
                sh ''' 
                    #!/bin/bash
                    ls -lrt
                    sleep 5
                    echo $BUILD_STAGE2 
                '''
            }
        }
        stage('Deploy') { 
            steps {
                script {
                    echo "${env.TEST1}"
                }
            
            }
        }
    }
}